gr1810/gr1810/urls.py
from django.contrib import admin
from django.urls import path, include
from user_management import views
import django.contrib.auth.urls

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
    path("", include("first_project.urls")),
    path("moviefacts/", include("moviefacts.urls")),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("accounts/", include("django.contrib.auth.urls")),
]

gr1810/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path('', views.index, name="index"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("user/", views.user_name, name="user_name"),
    path("<str:user_name>/thanks/", views.thanks, name="thanks"),
    path("api/v1/questions/", views.question_collection),
    path("api/v1/questions/<int:pk>/", views.question_element)
]

gr1810/polls/models.py
import datetime
from zoneinfo import ZoneInfo

from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200, null=False)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return f"Question: id: {self.id}, text: {self.question_text}"

    def was_published_recently(self):
        return self.pub_date >= datetime.datetime.now(tz=ZoneInfo("UTC")) - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return f"Choice: id: {self.id}, text: {self.choice_text}"


gr1810/polls/forms.py
from django import forms

class NameForm(forms.Form):
    your_name = forms.CharField(label="Your name", max_length=100)
    birthday = forms.DateField(label="birthday: ", widget=forms.SelectDateWidget)
    email = forms.EmailField(label="your email: ")


gr1810/polls/views.py
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .forms import NameForm
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import QuestionSerializer
from .models import Question, Choice


def index(request: HttpRequest) -> HttpResponse:
    latest_questions = Question.objects.order_by("-pub_date")[:5]
    context = {
        "latest_questions": latest_questions
    }
    return render(request, "polls/index.html", context)


def detail(request: HttpRequest, question_id: int) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})


def results(request: HttpRequest, question_id: int) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request: HttpRequest, question_id: int) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/detail.html", {
            "question": question,
            "error_message": "You didn`t select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question_id,))) # /polls/3/results/


def user_name(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = NameForm(request.POST)
        if form.is_valid():
            your_name = form.cleaned_data["your_name"]
            return HttpResponseRedirect(f"/polls/{your_name}/thanks/")
    else:
        form = NameForm()
    return render(request, "polls/user_name.html", {"form": form})


def thanks(request: HttpRequest, user_name: str) -> HttpResponse:
    return render(request, "polls/thanks.html", {"user_name": user_name})


@api_view(['GET'])
def question_collection(request):
    if request.method == 'GET':
        questions = Question.objects.all()
        serializer = QuestionSerializer(questions, many=True)
        return Response(serializer.data)


@api_view(['GET'])
def question_element(request, pk):
    try:
        question = Question.objects.get(pk=pk)
    except:
        return HttpResponse(status=404)
    
    if request.method == 'GET':
        serializer = QuestionSerializer(question)
        return Response(serializer.data)

gr1810/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Polls</title>
</head>

<body>
    {% block heading %}
    <h2>Polls</h2>
    {% endblock heading %}

    {% block content %}

    {% endblock content %}
</body>

</html>

gr1810/polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block heading %}
{{ block.super }}
<h3>poll {{question.question_text}}</h3>
{% endblock heading %}

{% block content %}
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend>
        <h2>{{ question.question_text }}</h2>
    </legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

{% endblock content %}

gr1810/polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block heading %}
{{ block.super }}
<h3>latest</h3>
{% endblock heading %}

{% block content %}
{% if latest_questions %}
<ul>
    {% for question in latest_questions %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a> </li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available</p>
{% endif %}

{% endblock content %}


gr1810/polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block heading %}
{{ block.super }}
<h3>result - {{question.question_text}}</h3>
{% endblock heading %}

{% block content %}
<ul>
    {% for choice in question.choice_set.all %}
    <li>
        {{ choice.choice_text }} -- {{ choice.votes }}
    </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock content %}

gr1810/polls/templates/polls/thanks.html
{% extends "polls/base.html" %}

{% block heading %}
{{ block.super }}
<h3>Thanks!</h3>
{% endblock heading %}

{% block content %}
<br>
<p>
    <h4>{{ user_name }}! Thank you for registering))</h4>
</p>

{% endblock content %}

gr1810/polls/templates/polls/user_name.html
{% extends "polls/base.html" %}

{% block heading %}
{{ block.super }}
<h3>FORM</h3>
{% endblock heading %}

{% block content %}
<form action="{% url 'polls:user_name' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock content %}